apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: example-pipiline
  labels:
    app: example-pipeline
spec:
  params:
  - name: REVISION
    value: main
  pipelineSpec:
    params:
      - name: REVISION
        type: string
        description: Revision to checkout. (branch, tag, sha, ref, etc...)
        default: ""
    tasks:
    - name: git-clone-sourcecode
      taskRef:
        resolver: cluster
        params:
        - name: name
          value: git-clone
        - name: kind
          value: task
        - name: namespace
          value: default
      workspaces:
      - name: output
        workspace: source-volume
      params:
      - name: url
        value: https://mirror.ghproxy.com/https://github.com/shadowmktk/demo-user-project
      - name: revision
        value: $(params.REVISION)
      - name: subdirectory
        value: sourcecode
    - name: git-clone-deployment
      runAfter:
      - git-clone-sourcecode
      taskRef:
        resolver: cluster
        params:
        - name: name
          value: git-clone
        - name: kind
          value: task
        - name: namespace
          value: default
      workspaces:
      - name: output
        workspace: source-volume
      params:
      - name: url
        value: https://mirror.ghproxy.com/https://github.com/shadowmktk/demo-user-deployments
      - name: revision
        value: $(params.REVISION)
      - name: subdirectory
        value: deployment
    - name: manifest-update
      runAfter:
      - git-clone-deployment
      taskRef:
        resolver: cluster
        params:
        - name: name
          value: git-cli
        - name: kind
          value: task
        - name: namespace
          value: default
      workspaces:
      - name: source
        workspace: source-volume
      - name: ssh-directory
        workspace: ssh-directory
      params:
      - name: BASE_IMAGE
        value: registry.cn-hangzhou.aliyuncs.com/cloud-native-cn/git-cli:root-2.39
      - name: GIT_USER_NAME
        value: pipelinerobot
      - name: GIT_USER_EMAIL
        value: pipelinerobot@nautes.io
      - name: GIT_SCRIPT
        value: |
          ls -al ~/.ssh
          git clone https://mirror.ghproxy.com/https://github.com/shadowmktk/demo-user-deployments
          ls -lh
          ls -lh demo-user-deployments
      
    workspaces:
    - name: source-volume
  workspaces:
  - name: source-volume
    persistentVolumeClaim:
      claimName: source-pvc
  - name: ssh-directory
    secret:
      secretName: gitlab-ssh-key
